name: app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  change_app_package_name: ^1.1.0
  connectivity_plus: ^2.3.4
  firebase_auth: ^3.3.20
  firebase_core: ^1.17.1
  firebase_remote_config: ^2.0.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_facebook_auth: ^4.3.4+2
  flutter_form_builder: ^7.3.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.3+1
  font_awesome_flutter: ^10.1.0
  form_builder_validators: ^8.1.1
  google_sign_in: ^5.3.3
  http: ^0.13.4
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/env/
